import seedRouter from "./routes/seed.js";
import "dotenv/config";
import express from "express";
import cors from "cors";
import productsRouter from "./routes/products.js";
import ordersRouter from "./routes/orders.js";
const app = express();
app.use(cors({ origin: process.env.FRONTEND_URL || "*" }));
app.use(express.json());
app.use("/api/seed", seedRouter);
app.get("/api/health", (req, res) => res.json({ status: "ok" }));
app.use("/api/products", productsRouter);
app.use("/api/orders", ordersRouter);
const port = process.env.PORT || 4000;
app.listen(port, () => console.log(`Urban Caps API en écoute sur http://localhost:${port}`));
